controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

pattern_index:
    path: /pattern
    controller: App\Controller\PatternController::index
